### ISSUE TITLE
Add ability to change online server address

### ISSUE THREAD

**Issue by dougdonohoe** [dougdonohoe/ddpoker#1]
The current code hardcodes the backend server used for online game registration and the chat lobby in `code/poker/src/main/resources/config/poker/client.properties`:

```
settings.online.enabled=true
settings.online.server= http://free.ddpoker.com:80/poker/servlet/
settings.online.chat=	free.ddpoker.com:11886
```

These servers don't exist, which can cause a delay on startup as the game times out trying to reach them.

With the code now open-sourced, folks will be running their own servers, so it would be nice to be able to set the server address or IP (and port) in the UI.  It would also be nice to toggle the enabled flag.

Options might be the best place to add this, but it doesn't necessarily resolve the startup hanging issue.  It might make sense to default `settings.online.enable` to false.

**Comment by Mudr0x** [comment]
👍

**Comment by dougdonohoe** [comment]
Fixed in https://github.com/dougdonohoe/ddpoker/pull/3
