### ISSUE TITLE
Could not resolve dependencies for project com.donohoedigital:gui:jar:3.0

### ISSUE THREAD

**Issue by Mudr0x** [dougdonohoe/ddpoker#2]
Hello,

Thanks to share your work!

I'm not a Mac user and I'm trying to build it under Windows or Linux.
I strctly respected your install process either under Windows with IntelliJ or under Ubuntu and I almost good for all, but in both it fails when compiling it (mvn-package-notests under Linux) with a missing dependency error:

```
Could not resolve dependencies for project com.donohoedigital:gui:jar:3.0 
   dependency: apple:ui:jar:1.4.1 (compile)
     apple:ui:jar:1.4.1 was not found in https://repo.maven.apache.org/maven2  ....
```

After taking a look at the pom.xml of the ui module:

```
<profiles>
    <!-- Use our fake apple.jar so we can compile on non-mac platforms -->
    <profile>

      <id>Apple Integration</id>
      <activation>
        <os>
          <family>!mac</family>
        </os>
      </activation>

      <dependencies>
        <dependency>
          <groupId>apple</groupId>
          <artifactId>ui</artifactId>
          <version>1.4.1</version>
        </dependency>
      </dependencies>
    </profile>
  </profiles>
```

I understood that it is a fake apple:ui dependency, but I see no way to compile and build it, or is there a missing 'apple.jar'?
Thanks for clarification.

**Comment by dougdonohoe** [comment]
I had to refresh my memory.  I don't have a windows or linux platform, so as I've noted, I haven't tested there.

This has to do with the `MacApplication` class and its import of `import com.apple.eawt.*;`.  What I probably did in the past was mocked these out, but I don't recall how.

A temporary workaround is to comment out that import line since that class is only loaded, dynamically in this code in `code/gui/src/main/java/com/donohoedigital/gui/BaseApp.java`, and since you aren't on a Mac, it won't be run.

```
     if (Utils.ISMAC && !bHeadless) // start MacApplication
            Class<?> cMac = ConfigUtils.getClass("com.donohoedigital.gui.mac.MacApplication", true);
```

I'll think if there is a better way to fix this.

**Comment by dougdonohoe** [comment]
Maybe there is a way to exclude compiling `MacApplication` on non-mac platforms.  My maven is rusty, but maybe ChatGPT can help.

**Comment by dougdonohoe** [comment]
Try this:

```
<profiles>
    <profile>
        <id>mac</id>
        <activation>
            <os>
                <family>!mac</family>
            </os>
        </activation>
        <build>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <excludes>
                            <exclude>**/com/donohoedigital/gui/mac/MacApplication.java</exclude>
                        </excludes>
                    </configuration>
                </plugin>
            </plugins>
        </build>
    </profile>
</profiles>
```

**Comment by dougdonohoe** [comment]
Fixed with that maven suggestion.

**Comment by Mudr0x** [comment]
Thanks for your fix, I can compile now under Windows or Linux.  😃
