### ISSUE TITLE
Help! with online game hosting

### ISSUE THREAD

**Issue by Mudr0x** [dougdonohoe/ddpoker#5]
Hello,

I succeed to install and host my own pokerserver and pokerweb on https://ddpoker.openholdembot.com/ (as you can see), and build the java client for Windows, correctly connect it to my pokerserver and create my ddpoker account,, other friends also succeed to create their accounts.
But when we want to create our online game and first test the connection on online tournament setup it fails with a timeout error:

![Screenshot 2024-08-24 1130151](https://github.com/user-attachments/assets/36d56c2d-5793-4f91-a1ec-4a914c394176)

Even when I try disabling completely my firewall, and even if we finally create our online game and others want to connect on, we have the same error.

Maybe it is because, I host an apache server running on 8080 port, for my main domain so I installed my ddpoker project on a sub-domain where I host the tomcat server running on another port (8088) proxy reversed by the apache server, so maybe I miss some setups to handle this on the client side? But I don't see where because I think I correctly adapted all server and email settings with my own...
Would it be necessary to do a port forwarding on the server side? And if so, what is it?
Thanks to help me I'm a little lost because even if I debug from my side with IntelliJ I only retrieve this error msg from the server and on server log there is just this same timeout error.

**Comment by dougdonohoe** [comment]
Basically, an attempt is being made to contact the computer running DD Poker from your backend server, and it is failing.

See https://ddpoker.openholdembot.com/support/onlinesupplement for our old advice on what is going on here.

Your server setup shouldn't matter with regard to ports as all it is trying to do is contact the public IP of the host.  You should be able to ping that IP and telnet to the IP/port as a test.

**Comment by dougdonohoe** [comment]
Closing since no real action items for DD Poker project.
